# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee63a21e665fac96b7273f7e0769b089b2560a029ba07c28dd88ab32adec9b2e7c2c83bca76bcbc86c4393c53741ee0453a72d02c3c6c833a79f8bd43e64eef2
  otp_key: fc2da60792d7ecf51b0cbbef62e5c69a
test:
  secret_key_base: a6a9af2603c15d2209d7b40fc3cfe931d1e614d0f727520f4e11157007623e5105a91a32e51a039283dfae4af795f5d43247fa3b485a88433f14bb05bcaee924

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
